name:                algorithmic-puzzles
version:             0.1.0.0
github:              "jarnoleconte/algorithmic-puzzles"
license:             BSD3
author:              "Jarno Le Conté"
maintainer:          "jarno.leconte@me.com"
copyright:           "2018 Jarno Le Conté"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jarnoleconte/algorithmic-puzzles#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  001-wolf-goat-cabbage:
    main:                Main.hs
    source-dirs:         001-wolf-goat-cabbage
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  002-glove-selection:
    main:                Main.hs
    source-dirs:         002-glove-selection
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

